### ISSUE TITLE
Package that's clearly outdated shows up as "Up-to-date"

### ISSUE THREAD

**Issue by teeberg** [dependencies-io/www.dependencies.io#38]
![image](https://user-images.githubusercontent.com/199071/37881230-9eaf6778-3049-11e8-92eb-111a49c0d78c.png)

but the last version is `1.14.63`: https://pypi.python.org/pypi/awscli

We do pin it to `1.14.0` in our `requirements.txt` (since that's generated from a `requirements.in` via `pip-compile`)... is it trying to respect that constraint? Or is it because we configured the `dependencies.yml` to not include that package? In which case it'd seem to be misleading, since it's not up-to-date, just excluded from the config.

**Comment by davegaeddert** [comment]
Agreed that is misleading. It is showing that you're using the latest update available of what you've asked for, so if you've excluded it, then there is no "suggested update". I've removed the text from there for now so that it looks more like "there is no suggested update". In the future we should be able to give better reasoning, tie it into your config settings to show why, etc.
